# Generated by Django 5.0.6 on 2024-07-03 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0002_tempuser_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempuser',
            name='mobile_Number',
        ),
    ]
